config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'

  get '/about', to: 'pages#about'
  get '/help',  to: 'pages#help'

  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:edit, :update, :show, :destroy]

  def new
    @todo = Todo.new
  end

  def index
    @todos = Todo.all
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      flash[:notice] = "Todo was created successfully!"
      redirect_to todo_path(@todo)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      flash[:notice] = "Todo was updated successfully!"
      redirect_to todo_path(@todo)
    else
      render 'edit'
    end
  end

  def destroy
    @todo.destroy
    flash[:notice] = "Todo was deleted successfully!"
    redirect_to todos_path
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, message| %>
  <ul>
    <li><%= message %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tigershark</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<h3>Version 0.0.1</h3>

app/views/pages/help.html.erb
<h1>Help</h1>

<h3>Uh oh, I think you're on your own...</h3>

app/views/pages/home.html.erb
<h1 style="color: red">Homepage!</h1>

<p>
  <a href="/about">
    About this site
  </a>
</p>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
  <h2>The following errors have occurred:</h2>
  <ul>
    <% @todo.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @todo do |form| %>
  <p>
    <%= form.label :name %> <br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :description %> <br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back to Todos listing', todos_path %>

app/views/todos/edit.html.erb
<h1>Edit an existing Todo</h1>

<%= render 'form' %>

app/views/todos/index.html.erb
<h1>Listing all Todos</h1>

<p><%= link_to "Create a Todo", new_todo_path %></p>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  <tr>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.name %></td>
        <td><%= todo.description %></td>
        <td><%= link_to "Edit", edit_todo_path(todo) %></td>
        <td><%= link_to "Show", todo_path(todo) %></td>
        <td><%= link_to "Delete", todo_path(todo), method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tr>
</table>

app/views/todos/new.html.erb
<h1>Create a new Todo</h1>

<%= render 'form' %>

app/views/todos/show.html.erb
<h1>Showing a Todo</h1>

<p>
  Name: <%= @todo.name %>
</p>
<p>
  Description: <%= @todo.description %>
</p>

<%= link_to 'Edit this Todo', edit_todo_path(@todo) %> |
<%= link_to 'Back to Todos listing', todos_path %>